controller_manager:
  ros__parameters:
    update_rate: 100
    omni_velocity_controller:
      type: semubot_velocity_controller/SemubotVelocityController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

omni_velocity_controller:
  ros__parameters:
    wheel_radius: 0.05
    base_radius: 0.15
    wheel_names:
      - omni_ball_1_joint 
      - omni_ball_2_joint
      - omni_ball_3_joint
    max_linear_velocity: 1.0
    max_angular_velocity: 2.0

    kp: 0.001
    ki: 0.0
    kd: 0.0

joint_state_broadcaster:
  ros__parameters:
    joints:
      - omni_ball_1_joint
      - omni_ball_2_joint
      - omni_ball_3_joint